nome= input ("informe seu nome:")
dia= input ("informe o dia que voce nasceu:")
mes= input ("informe o mes: ")
ano= input ("informe o ano:")
print ("olá {}. Voce nasceu em {} do {} de {}". format (nome,dia,mes,ano))
